# Generated by Django 4.1.3 on 2024-08-23 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_name', models.CharField(max_length=113)),
                ('archetype_for_NPC', models.BooleanField(default=False)),
                ('archetype_force_sensitive', models.BooleanField(blank=True, default=False)),
                ('archetype_dexterity', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_knowledge', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_mechanical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_perception', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_strength', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_technical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_force_control', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_force_sense', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_force_alter', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('archetype_starting_credits', models.IntegerField(blank=True, default=0, null=True)),
                ('archetype_personality', models.CharField(blank=True, max_length=1369)),
                ('archetype_background', models.CharField(blank=True, max_length=1369)),
                ('archetype_objectives', models.CharField(blank=True, max_length=1369)),
                ('archetype_a_quote', models.CharField(blank=True, max_length=1369)),
                ('archetype_game_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('archetype_source', models.CharField(blank=True, max_length=1369, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=113, unique=True)),
                ('NPC', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=223)),
                ('name', models.CharField(max_length=69)),
                ('species', models.CharField(max_length=69)),
                ('homeworld', models.CharField(max_length=69)),
                ('gender', models.CharField(max_length=13)),
                ('age', models.IntegerField(default=21)),
                ('height', models.CharField(max_length=13)),
                ('weight', models.CharField(max_length=13)),
                ('physical_description', models.CharField(max_length=1369)),
                ('personality', models.CharField(max_length=1369)),
                ('background', models.CharField(max_length=1369)),
                ('objectives', models.CharField(max_length=1369)),
                ('a_quote', models.CharField(max_length=1369)),
                ('credits', models.IntegerField(default=0)),
                ('force_sensitive', models.BooleanField(default=False)),
                ('dexterity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('knowledge', models.DecimalField(decimal_places=1, max_digits=3)),
                ('mechanical', models.DecimalField(decimal_places=1, max_digits=3)),
                ('perception', models.DecimalField(decimal_places=1, max_digits=3)),
                ('strength', models.DecimalField(decimal_places=1, max_digits=3)),
                ('technical', models.DecimalField(decimal_places=1, max_digits=3)),
                ('force_control', models.DecimalField(decimal_places=1, max_digits=3)),
                ('force_sense', models.DecimalField(decimal_places=1, max_digits=3)),
                ('force_alter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('force_points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('dark_side_points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('force_strength', models.DecimalField(decimal_places=1, max_digits=3)),
                ('archetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='DsixRPGcompanionBE.archetype')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_code', models.DecimalField(decimal_places=1, max_digits=3)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_skills', to='DsixRPGcompanionBE.character')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=69)),
                ('skill_name', models.CharField(max_length=69)),
                ('time_taken', models.CharField(blank=True, max_length=369, null=True)),
                ('is_a_reaction', models.BooleanField(default=False)),
                ('force_skill', models.BooleanField(default=False)),
                ('specializations_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('modifiers', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_use_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_game_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_code', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=113)),
                ('handle', models.CharField(blank=True, max_length=113, null=True)),
                ('bio', models.CharField(blank=True, max_length=113, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('game_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=223)),
                ('specialization_code', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('character_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='DsixRPGcompanionBE.characterskill')),
            ],
            options={
                'verbose_name': 'Skill Specialization',
                'verbose_name_plural': 'Skill Specializations',
            },
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_characters', to='DsixRPGcompanionBE.skill'),
        ),
        migrations.CreateModel(
            name='CharacterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=69)),
                ('private', models.BooleanField(default=False)),
                ('is_adventure_party', models.BooleanField(default=False)),
                ('characters', models.ManyToManyField(related_name='user_groups', to='DsixRPGcompanionBE.character')),
                ('game_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_groups', to='DsixRPGcompanionBE.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to='DsixRPGcompanionBE.user')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(through='DsixRPGcompanionBE.CharacterSkill', to='DsixRPGcompanionBE.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='DsixRPGcompanionBE.user'),
        ),
    ]
