# Generated by Django 4.1.3 on 2024-08-14 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archetype_name', models.CharField(max_length=113)),
                ('archetype_personality', models.CharField(max_length=1369)),
                ('archetype_background', models.CharField(max_length=1369)),
                ('archetype_objectives', models.CharField(max_length=1369)),
                ('archetype_a_quote', models.CharField(max_length=1369)),
                ('archetype_force_sensitive', models.BooleanField(default=False)),
                ('archetype_dexiterity', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_knowledge', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_mechanical', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_perception', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_strength', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_technical', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_force_control', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_force_sense', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_force_alter', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype_starting_credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=69)),
                ('skill_name', models.CharField(max_length=69)),
                ('time_taken', models.CharField(blank=True, max_length=369, null=True)),
                ('is_a_reaction', models.BooleanField(default=False)),
                ('force_skill', models.BooleanField(default=False)),
                ('specializations', models.CharField(blank=True, max_length=3666, null=True)),
                ('modifiers', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_use_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_game_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_code', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=113, unique=True)),
                ('NPC', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=223)),
                ('name', models.CharField(max_length=69)),
                ('species', models.CharField(max_length=69)),
                ('homeworld', models.CharField(max_length=69)),
                ('gender', models.CharField(max_length=13)),
                ('age', models.IntegerField(default=21)),
                ('height', models.CharField(max_length=13)),
                ('weight', models.CharField(max_length=13)),
                ('physical_description', models.CharField(max_length=1369)),
                ('personality', models.CharField(max_length=1369)),
                ('background', models.CharField(max_length=1369)),
                ('objectives', models.CharField(max_length=1369)),
                ('a_quote', models.CharField(max_length=1369)),
                ('credits', models.IntegerField(default=0)),
                ('force_sensitive', models.BooleanField(default=False)),
                ('dexterity', models.DecimalField(decimal_places=2, max_digits=2)),
                ('knowledge', models.DecimalField(decimal_places=2, max_digits=2)),
                ('mechanical', models.DecimalField(decimal_places=2, max_digits=2)),
                ('perception', models.DecimalField(decimal_places=2, max_digits=2)),
                ('strength', models.DecimalField(decimal_places=2, max_digits=2)),
                ('technical', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_control', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_sense', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_alter', models.DecimalField(decimal_places=2, max_digits=2)),
                ('force_points', models.DecimalField(decimal_places=1, max_digits=2)),
                ('dark_side_points', models.DecimalField(decimal_places=1, max_digits=2)),
                ('force_strength', models.DecimalField(decimal_places=1, max_digits=2)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='DsixRPGcompanionBE.archetype')),
            ],
        ),
    ]
