# Generated by Django 4.1.3 on 2024-08-16 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0003_characterskill_character_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='specializations',
        ),
        migrations.CreateModel(
            name='SkillSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization_name', models.CharField(max_length=223)),
                ('specialization_code', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('character_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='DsixRPGcompanionBE.characterskill')),
            ],
            options={
                'verbose_name': 'Skill Specialization',
                'verbose_name_plural': 'Skill Specializations',
            },
        ),
    ]
