# Generated by Django 4.1.3 on 2024-08-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0004_remove_skill_specializations_skillspecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='specializations_notes',
            field=models.CharField(blank=True, max_length=3666, null=True),
        ),
    ]
