# Generated by Django 4.1.3 on 2024-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterskill',
            name='attribute',
            field=models.CharField(default='Knowledge', max_length=69),
        ),
    ]
