# Generated by Django 4.1.3 on 2024-08-16 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0005_skill_specializations_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=113)),
                ('bio', models.CharField(max_length=113)),
                ('admin', models.BooleanField(default=False)),
                ('game_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=69)),
                ('private', models.BooleanField(default=False)),
                ('is_adventure_party', models.BooleanField(default=False)),
                ('characters', models.ManyToManyField(related_name='user_groups', to='DsixRPGcompanionBE.character')),
                ('game_master', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_master_in_group', to='DsixRPGcompanionBE.user')),
                ('users', models.ManyToManyField(related_name='user_groups', to='DsixRPGcompanionBE.user')),
            ],
        ),
    ]
