# Generated by Django 4.1.3 on 2024-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0006_user_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.CharField(default=1, max_length=113, unique=True),
            preserve_default=False,
        ),
    ]
