# Generated by Django 4.1.3 on 2024-09-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0007_alter_characterskill_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='a_quote',
            field=models.CharField(blank=True, max_length=2369, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, max_length=2369, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='objectives',
            field=models.CharField(blank=True, max_length=2369, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.CharField(blank=True, max_length=2369, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='physical_description',
            field=models.CharField(blank=True, max_length=2369, null=True),
        ),
    ]
