# Generated by Django 4.1.3 on 2024-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0008_alter_character_a_quote_alter_character_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
