# Generated by Django 4.1.3 on 2024-10-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0009_character_skill_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=113, unique=True)),
                ('playable', models.BooleanField(default=False)),
                ('image', models.CharField(blank=True, max_length=223, null=True)),
                ('name', models.CharField(blank=True, max_length=69, null=True)),
                ('species_name', models.CharField(blank=True, max_length=69, null=True)),
                ('species_homeworld', models.CharField(blank=True, max_length=69, null=True)),
                ('species_average_height', models.CharField(blank=True, max_length=13, null=True)),
                ('species_average_weight', models.CharField(blank=True, max_length=13, null=True)),
                ('species_force_sensitive', models.BooleanField(blank=True, default=False, null=True)),
                ('species_dexterity_modifer', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_knowledge', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_mechanical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_perception', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_strength', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_technical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_force_control', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_force_sense', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_force_alter', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_force_points', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_dark_side_points', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_physical_description', models.CharField(blank=True, max_length=2369, null=True)),
                ('species_personality', models.CharField(blank=True, max_length=2369, null=True)),
                ('species_background', models.CharField(blank=True, max_length=2369, null=True)),
                ('species_force_strength', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('species_specific', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=69)),
                ('ability_name', models.CharField(max_length=69)),
                ('time_taken', models.CharField(blank=True, max_length=369, null=True)),
                ('is_a_reaction', models.BooleanField(default=False)),
                ('force_skill', models.BooleanField(default=False)),
                ('special_ability_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('modifiers', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_use_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_game_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_code', models.DecimalField(decimal_places=1, max_digits=3)),
                ('species_specific', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_abilities', to='DsixRPGcompanionBE.species')),
            ],
        ),
    ]
