# Generated by Django 4.1.3 on 2024-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0009_user_handle_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archetype',
            old_name='archetype_dexiterity',
            new_name='archetype_dexterity',
        ),
        migrations.AddField(
            model_name='archetype',
            name='archetype_game_notes',
            field=models.CharField(blank=True, max_length=3666, null=True),
        ),
    ]
