# Generated by Django 4.1.3 on 2024-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0011_rename_species_dexterity_modifer_species_species_dexterity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_specific',
        ),
        migrations.AddField(
            model_name='species',
            name='species_appeared_in',
            field=models.CharField(blank=True, max_length=2369, null=True),
        ),
    ]
