# Generated by Django 4.1.3 on 2024-08-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0012_alter_archetype_archetype_dexterity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='archetype_source',
            field=models.CharField(blank=True, max_length=1369, null=True),
        ),
    ]
