# Generated by Django 4.1.3 on 2024-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0013_archetype_archetype_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='archetype_for_NPC',
            field=models.BooleanField(default=False),
        ),
    ]
