# Generated by Django 4.1.3 on 2024-11-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0013_alter_species_species_average_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_average_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_average_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
