# Generated by Django 4.1.3 on 2024-08-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0014_archetype_archetype_for_npc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archetype',
            name='archetype_a_quote',
            field=models.CharField(blank=True, max_length=1369),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_background',
            field=models.CharField(blank=True, max_length=1369),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_dexterity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_force_alter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_force_control',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_force_sense',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_force_sensitive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_knowledge',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_mechanical',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_objectives',
            field=models.CharField(blank=True, max_length=1369),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_perception',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_personality',
            field=models.CharField(blank=True, max_length=1369),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_starting_credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_strength',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='archetype_technical',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
