# Generated by Django 4.1.3 on 2024-08-22 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0015_alter_archetype_archetype_a_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='archetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='DsixRPGcompanionBE.archetype'),
        ),
    ]
