# Generated by Django 4.1.3 on 2024-12-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0015_characterspecies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species', to='DsixRPGcompanionBE.species'),
        ),
    ]
