# Generated by Django 4.1.3 on 2024-12-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0017_alter_character_species_delete_characterspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='archetype_allowed_species',
            field=models.ManyToManyField(blank=True, related_name='archetypes', to='DsixRPGcompanionBE.species'),
        ),
    ]
