# Generated by Django 4.1.3 on 2025-01-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0018_archetype_archetype_allowed_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=69)),
                ('ability_name', models.CharField(max_length=69)),
                ('time_taken', models.CharField(blank=True, max_length=369, null=True)),
                ('is_a_reaction', models.BooleanField(default=False)),
                ('force_skill', models.BooleanField(default=False)),
                ('species_specific', models.BooleanField(default=False)),
                ('special_ability_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('modifiers', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_use_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_game_notes', models.CharField(blank=True, max_length=3666, null=True)),
                ('skill_code', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='species_skills',
            field=models.ManyToManyField(blank=True, related_name='species', to='DsixRPGcompanionBE.skill'),
        ),
        migrations.DeleteModel(
            name='SpecialAbility',
        ),
        migrations.AddField(
            model_name='species',
            name='species_abilities',
            field=models.ManyToManyField(blank=True, related_name='species', to='DsixRPGcompanionBE.ability'),
        ),
    ]
