# Generated by Django 4.1.3 on 2025-01-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0019_ability_species_species_skills_delete_specialability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='species_abilities',
            new_name='species_ability',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='species_skills',
            new_name='species_skill',
        ),
    ]
