# Generated by Django 4.1.3 on 2025-01-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0020_rename_species_abilities_species_species_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='special_ability_notes',
            new_name='ability_notes',
        ),
    ]
