# Generated by Django 4.1.3 on 2025-01-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0021_rename_special_ability_notes_ability_ability_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='skill_code',
            new_name='ability_code',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='skill_game_notes',
            new_name='ability_game_notes',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='skill_use_notes',
            new_name='ability_use_notes',
        ),
    ]
