# Generated by Django 4.1.3 on 2025-01-24 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0022_rename_skill_code_ability_ability_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='force_skill',
            new_name='force_ability',
        ),
    ]
