# Generated by Django 4.1.3 on 2025-01-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0023_rename_force_skill_ability_force_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='source',
            field=models.CharField(blank=True, max_length=1369, null=True),
        ),
    ]
