# Generated by Django 4.1.3 on 2025-01-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0025_rename_source_ability_ability_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='species_skill',
            field=models.BooleanField(default=False),
        ),
    ]
