# Generated by Django 4.1.3 on 2025-01-27 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0027_remove_species_species_ability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='species_ability',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_skill',
        ),
        migrations.AddField(
            model_name='ability',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilites', to='DsixRPGcompanionBE.species'),
        ),
    ]
