# Generated by Django 4.1.3 on 2025-01-27 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0028_remove_species_species_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='species_skill',
            new_name='species_specific',
        ),
        migrations.AddField(
            model_name='skill',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='DsixRPGcompanionBE.species'),
        ),
    ]
