# Generated by Django 4.1.3 on 2025-03-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0030_ability_home_brew_skill_home_brew_skill_skill_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_background',
            field=models.CharField(blank=True, max_length=3696, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_personality',
            field=models.CharField(blank=True, max_length=3696, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_physical_description',
            field=models.CharField(blank=True, max_length=3696, null=True),
        ),
    ]
