# Generated by Django 4.1.3 on 2025-04-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0031_alter_species_species_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_average_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='species_average_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
