# Generated by Django 5.2 on 2026-04-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DsixRPGcompanionBE', '0032_alter_species_species_average_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='archetype_imperial',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='archetype',
            name='archetype_playable',
            field=models.BooleanField(default=True),
        ),
    ]
